export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEEK_WEATHER = 'GET_WEEK_WEATHER';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_MESSAGE = 'SET_MESSAGE';
export const REDIRECT = 'REDIRECT';